In [5]:
%pip install hvplot

Collecting hvplot
  Downloading hvplot-0.12.2-py3-none-any.whl.metadata (19 kB)
Collecting bokeh>=3.1 (from hvplot)
  Downloading bokeh-3.9.2-py3-none-any.whl.metadata (10 kB)
Collecting colorcet>=2 (from hvplot)
  Downloading colorcet-3.2.1-py3-none-any.whl.metadata (6.3 kB)
Collecting holoviews>=1.19.0 (from hvplot)
  Downloading holoviews-1.23.1-py3-none-any.whl.metadata (7.8 kB)
Requirement already satisfied: numpy>=1.21 in C:\Users\secar\miniconda3\Lib\site-packages (from hvplot) (2.5.1)
Requirement already satisfied: packaging in C:\Users\secar\miniconda3\Lib\site-packages (from hvplot) (26.0)
Requirement already satisfied: pandas>=1.3 in C:\Users\secar\miniconda3\Lib\site-packages (from hvplot) (3.0.3)
Collecting panel>=1.0 (from hvplot)
  Downloading panel-1.9.3-py3-none-any.whl.metadata (15 kB)
Collecting param<3.0,>=1.12.0 (from hvplot)
  Downloading param-2.4.1-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: Jinja2>=2.9 in C:\Users\secar\miniconda3\Lib\site-packages (from bokeh>=3.1->hvplot) (3.1.6)
Collecting contourpy>=1.2 (from bokeh>=3.1->hvplot)
  Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting narwhals>=1.13 (from bokeh>=3.1->hvplot)
  Downloading narwhals-2.24.0-py3-none-any.whl.metadata (15 kB)
Collecting pillow>=7.1.0 (from bokeh>=3.1->hvplot)
  Downloading pillow-12.3.0-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
Requirement already satisfied: PyYAML>=3.10 in C:\Users\secar\miniconda3\Lib\site-packages (from bokeh>=3.1->hvplot) (6.0.3)
Requirement already satisfied: tornado>=6.2 in C:\Users\secar\miniconda3\Lib\site-packages (from bokeh>=3.1->hvplot) (6.5.7)
Collecting xyzservices>=2021.09.1 (from bokeh>=3.1->hvplot)
  Downloading xyzservices-2026.3.0-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\secar\miniconda3\Lib\site-packages (from holoviews>=1.19.0->hvplot) (2.9.0.post0)
Collecting pyviz-comms>=2.1 (from holoviews>=1.19.0->hvplot)
  Downloading pyviz_comms-3.0.6-py3-none-any.whl.metadata (7.7 kB)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\secar\miniconda3\Lib\site-packages (from Jinja2>=2.9->bokeh>=3.1->hvplot) (3.0.3)
Requirement already satisfied: tzdata in C:\Users\secar\miniconda3\Lib\site-packages (from pandas>=1.3->hvplot) (2026.2)
Collecting linkify-it-py (from panel>=1.0->hvplot)
  Downloading linkify_it_py-2.1.0-py3-none-any.whl.metadata (8.5 kB)
Collecting markdown (from panel>=1.0->hvplot)
  Downloading markdown-3.10.3-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: markdown-it-py in C:\Users\secar\miniconda3\Lib\site-packages (from panel>=1.0->hvplot) (4.0.0)
Collecting mdit-py-plugins (from panel>=1.0->hvplot)
  Downloading mdit_py_plugins-0.6.1-py3-none-any.whl.metadata (2.9 kB)
Collecting nh3 (from panel>=1.0->hvplot)
  Downloading nh3-0.3.6-cp38-abi3-win_amd64.whl.metadata (2.0 kB)
Collecting panel-material-ui>=0.10.0 (from panel>=1.0->hvplot)
  Downloading panel_material_ui-0.14.2-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: requests in C:\Users\secar\miniconda3\Lib\site-packages (from panel>=1.0->hvplot) (2.34.2)
Requirement already satisfied: tqdm in C:\Users\secar\miniconda3\Lib\site-packages (from panel>=1.0->hvplot) (4.68.2)
Requirement already satisfied: typing-extensions in C:\Users\secar\miniconda3\Lib\site-packages (from panel>=1.0->hvplot) (4.16.0)
Requirement already satisfied: six>=1.5 in C:\Users\secar\miniconda3\Lib\site-packages (from python-dateutil>=2.8.2->holoviews>=1.19.0->hvplot) (1.17.0)
Collecting uc-micro-py (from linkify-it-py->panel>=1.0->hvplot)
  Downloading uc_micro_py-2.0.0-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: mdurl~=0.1 in C:\Users\secar\miniconda3\Lib\site-packages (from markdown-it-py->panel>=1.0->hvplot) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\secar\miniconda3\Lib\site-packages (from requests->panel>=1.0->hvplot) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\secar\miniconda3\Lib\site-packages (from requests->panel>=1.0->hvplot) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\secar\miniconda3\Lib\site-packages (from requests->panel>=1.0->hvplot) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\secar\miniconda3\Lib\site-packages (from requests->panel>=1.0->hvplot) (2026.7.22)
Requirement already satisfied: colorama in C:\Users\secar\miniconda3\Lib\site-packages (from tqdm->panel>=1.0->hvplot) (0.4.6)
Downloading hvplot-0.12.2-py3-none-any.whl (180 kB)
Downloading param-2.4.1-py3-none-any.whl (151 kB)
Downloading bokeh-3.9.2-py3-none-any.whl (6.4 MB)
   ---------------------------------------- 0.0/6.4 MB ? eta -:--:--
   ---------------------------------------- 6.4/6.4 MB 71.7 MB/s  0:00:00
Downloading colorcet-3.2.1-py3-none-any.whl (262 kB)
Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Downloading holoviews-1.23.1-py3-none-any.whl (6.0 MB)
   ---------------------------------------- 0.0/6.0 MB ? eta -:--:--
   ---------------------------------------- 6.0/6.0 MB 99.3 MB/s  0:00:00
Downloading narwhals-2.24.0-py3-none-any.whl (461 kB)
Downloading panel-1.9.3-py3-none-any.whl (30.3 MB)
   ---------------------------------------- 0.0/30.3 MB ? eta -:--:--
   ------------------------------------ --- 27.8/30.3 MB 135.6 MB/s eta 0:00:01
   ---------------------------------------- 30.3/30.3 MB 92.2 MB/s  0:00:00
Downloading panel_material_ui-0.14.2-py3-none-any.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 1.7/1.7 MB 52.2 MB/s  0:00:00
Downloading pillow-12.3.0-cp314-cp314-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 7.2/7.2 MB 87.0 MB/s  0:00:00
Downloading pyviz_comms-3.0.6-py3-none-any.whl (84 kB)
Downloading xyzservices-2026.3.0-py3-none-any.whl (94 kB)
Downloading linkify_it_py-2.1.0-py3-none-any.whl (19 kB)
Downloading markdown-3.10.3-py3-none-any.whl (110 kB)
Downloading mdit_py_plugins-0.6.1-py3-none-any.whl (66 kB)
Downloading nh3-0.3.6-cp38-abi3-win_amd64.whl (624 kB)
   ---------------------------------------- 0.0/624.5 kB ? eta -:--:--
   ---------------------------------------- 624.5/624.5 kB 42.3 MB/s  0:00:00
Downloading uc_micro_py-2.0.0-py3-none-any.whl (6.4 kB)
Installing collected packages: xyzservices, uc-micro-py, pillow, param, nh3, narwhals, markdown, contourpy, colorcet, pyviz-comms, mdit-py-plugins, linkify-it-py, bokeh, panel-material-ui, panel, holoviews, hvplot

   ---- -----------------------------------  2/17 [pillow]
   ---- -----------------------------------  2/17 [pillow]
   ---- -----------------------------------  2/17 [pillow]
   ------- --------------------------------  3/17 [param]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   -------------- -------------------------  6/17 [markdown]
   ---------------- -----------------------  7/17 [contourpy]
   ------------------ ---------------------  8/17 [colorcet]
   ----------------------- ---------------- 10/17 [mdit-py-plugins]
   ---------------------------- ----------- 12/17 [bokeh]
   ---------------------------- ----------- 12/17 [bokeh]
   ---------------------------- ----------- 12/17 [bokeh]
   ---------------------------- ----------- 12/17 [bokeh]
   ---------------------------- ----------- 12/17 [bokeh]
   ---------------------------- ----------- 12/17 [bokeh]
   ---------------------------- ----------- 12/17 [bokeh]
   ---------------------------- ----------- 12/17 [bokeh]
   ---------------------------- ----------- 12/17 [bokeh]
   ---------------------------- ----------- 12/17 [bokeh]
   ---------------------------- ----------- 12/17 [bokeh]
   ---------------------------- ----------- 12/17 [bokeh]
   ---------------------------- ----------- 12/17 [bokeh]
   ------------------------------ --------- 13/17 [panel-material-ui]
   ------------------------------ --------- 13/17 [panel-material-ui]
   -------------------------------- ------- 14/17 [panel]
   -------------------------------- ------- 14/17 [panel]
   -------------------------------- ------- 14/17 [panel]
   -------------------------------- ------- 14/17 [panel]
   -------------------------------- ------- 14/17 [panel]
   -------------------------------- ------- 14/17 [panel]
   -------------------------------- ------- 14/17 [panel]
   -------------------------------- ------- 14/17 [panel]
   -------------------------------- ------- 14/17 [panel]
   -------------------------------- ------- 14/17 [panel]
   -------------------------------- ------- 14/17 [panel]
   -------------------------------- ------- 14/17 [panel]
   -------------------------------- ------- 14/17 [panel]
   -------------------------------- ------- 14/17 [panel]
   -------------------------------- ------- 14/17 [panel]
   -------------------------------- ------- 14/17 [panel]
   -------------------------------- ------- 14/17 [panel]
   -------------------------------- ------- 14/17 [panel]
   -------------------------------- ------- 14/17 [panel]
   -------------------------------- ------- 14/17 [panel]
   -------------------------------- ------- 14/17 [panel]
   -------------------------------- ------- 14/17 [panel]
   -------------------------------- ------- 14/17 [panel]
   ----------------------------------- ---- 15/17 [holoviews]
   ----------------------------------- ---- 15/17 [holoviews]
   ----------------------------------- ---- 15/17 [holoviews]
   ----------------------------------- ---- 15/17 [holoviews]
   ----------------------------------- ---- 15/17 [holoviews]
   ----------------------------------- ---- 15/17 [holoviews]
   ----------------------------------- ---- 15/17 [holoviews]
   ----------------------------------- ---- 15/17 [holoviews]
   ----------------------------------- ---- 15/17 [holoviews]
   ----------------------------------- ---- 15/17 [holoviews]
   ----------------------------------- ---- 15/17 [holoviews]
   ----------------------------------- ---- 15/17 [holoviews]
   ----------------------------------- ---- 15/17 [holoviews]
   ----------------------------------- ---- 15/17 [holoviews]
   ----------------------------------- ---- 15/17 [holoviews]
   ----------------------------------- ---- 15/17 [holoviews]
   ----------------------------------- ---- 15/17 [holoviews]
   ------------------------------------- -- 16/17 [hvplot]
   ------------------------------------- -- 16/17 [hvplot]
   ---------------------------------------- 17/17 [hvplot]

Successfully installed bokeh-3.9.2 colorcet-3.2.1 contourpy-1.3.3 holoviews-1.23.1 hvplot-0.12.2 linkify-it-py-2.1.0 markdown-3.10.3 mdit-py-plugins-0.6.1 narwhals-2.24.0 nh3-0.3.6 panel-1.9.3 panel-material-ui-0.14.2 param-2.4.1 pillow-12.3.0 pyviz-comms-3.0.6 uc-micro-py-2.0.0 xyzservices-2026.3.0
Note: you may need to restart the kernel to use updated packages.

In [8]:
%pip install hvplot scikit-learn

Requirement already satisfied: hvplot in C:\Users\secar\miniconda3\Lib\site-packages (0.12.2)
Collecting scikit-learn
  Downloading scikit_learn-1.9.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: bokeh>=3.1 in C:\Users\secar\miniconda3\Lib\site-packages (from hvplot) (3.9.2)
Requirement already satisfied: colorcet>=2 in C:\Users\secar\miniconda3\Lib\site-packages (from hvplot) (3.2.1)
Requirement already satisfied: holoviews>=1.19.0 in C:\Users\secar\miniconda3\Lib\site-packages (from hvplot) (1.23.1)
Requirement already satisfied: numpy>=1.21 in C:\Users\secar\miniconda3\Lib\site-packages (from hvplot) (2.5.1)
Requirement already satisfied: packaging in C:\Users\secar\miniconda3\Lib\site-packages (from hvplot) (26.0)
Requirement already satisfied: pandas>=1.3 in C:\Users\secar\miniconda3\Lib\site-packages (from hvplot) (3.0.3)
Requirement already satisfied: panel>=1.0 in C:\Users\secar\miniconda3\Lib\site-packages (from hvplot) (1.9.3)
Requirement already satisfied: param<3.0,>=1.12.0 in C:\Users\secar\miniconda3\Lib\site-packages (from hvplot) (2.4.1)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.18.0-cp314-cp314-win_amd64.whl.metadata (61 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\secar\miniconda3\Lib\site-packages (from scikit-learn) (2.24.0)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: Jinja2>=2.9 in C:\Users\secar\miniconda3\Lib\site-packages (from bokeh>=3.1->hvplot) (3.1.6)
Requirement already satisfied: contourpy>=1.2 in C:\Users\secar\miniconda3\Lib\site-packages (from bokeh>=3.1->hvplot) (1.3.3)
Requirement already satisfied: pillow>=7.1.0 in C:\Users\secar\miniconda3\Lib\site-packages (from bokeh>=3.1->hvplot) (12.3.0)
Requirement already satisfied: PyYAML>=3.10 in C:\Users\secar\miniconda3\Lib\site-packages (from bokeh>=3.1->hvplot) (6.0.3)
Requirement already satisfied: tornado>=6.2 in C:\Users\secar\miniconda3\Lib\site-packages (from bokeh>=3.1->hvplot) (6.5.7)
Requirement already satisfied: xyzservices>=2021.09.1 in C:\Users\secar\miniconda3\Lib\site-packages (from bokeh>=3.1->hvplot) (2026.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\secar\miniconda3\Lib\site-packages (from holoviews>=1.19.0->hvplot) (2.9.0.post0)
Requirement already satisfied: pyviz-comms>=2.1 in C:\Users\secar\miniconda3\Lib\site-packages (from holoviews>=1.19.0->hvplot) (3.0.6)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\secar\miniconda3\Lib\site-packages (from Jinja2>=2.9->bokeh>=3.1->hvplot) (3.0.3)
Requirement already satisfied: tzdata in C:\Users\secar\miniconda3\Lib\site-packages (from pandas>=1.3->hvplot) (2026.2)
Requirement already satisfied: linkify-it-py in C:\Users\secar\miniconda3\Lib\site-packages (from panel>=1.0->hvplot) (2.1.0)
Requirement already satisfied: markdown in C:\Users\secar\miniconda3\Lib\site-packages (from panel>=1.0->hvplot) (3.10.3)
Requirement already satisfied: markdown-it-py in C:\Users\secar\miniconda3\Lib\site-packages (from panel>=1.0->hvplot) (4.0.0)
Requirement already satisfied: mdit-py-plugins in C:\Users\secar\miniconda3\Lib\site-packages (from panel>=1.0->hvplot) (0.6.1)
Requirement already satisfied: nh3 in C:\Users\secar\miniconda3\Lib\site-packages (from panel>=1.0->hvplot) (0.3.6)
Requirement already satisfied: panel-material-ui>=0.10.0 in C:\Users\secar\miniconda3\Lib\site-packages (from panel>=1.0->hvplot) (0.14.2)
Requirement already satisfied: requests in C:\Users\secar\miniconda3\Lib\site-packages (from panel>=1.0->hvplot) (2.34.2)
Requirement already satisfied: tqdm in C:\Users\secar\miniconda3\Lib\site-packages (from panel>=1.0->hvplot) (4.68.2)
Requirement already satisfied: typing-extensions in C:\Users\secar\miniconda3\Lib\site-packages (from panel>=1.0->hvplot) (4.16.0)
Requirement already satisfied: six>=1.5 in C:\Users\secar\miniconda3\Lib\site-packages (from python-dateutil>=2.8.2->holoviews>=1.19.0->hvplot) (1.17.0)
Requirement already satisfied: uc-micro-py in C:\Users\secar\miniconda3\Lib\site-packages (from linkify-it-py->panel>=1.0->hvplot) (2.0.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\secar\miniconda3\Lib\site-packages (from markdown-it-py->panel>=1.0->hvplot) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\secar\miniconda3\Lib\site-packages (from requests->panel>=1.0->hvplot) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\secar\miniconda3\Lib\site-packages (from requests->panel>=1.0->hvplot) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\secar\miniconda3\Lib\site-packages (from requests->panel>=1.0->hvplot) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\secar\miniconda3\Lib\site-packages (from requests->panel>=1.0->hvplot) (2026.7.22)
Requirement already satisfied: colorama in C:\Users\secar\miniconda3\Lib\site-packages (from tqdm->panel>=1.0->hvplot) (0.4.6)
Downloading scikit_learn-1.9.0-cp314-cp314-win_amd64.whl (8.3 MB)
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   ---------------------------------------- 8.3/8.3 MB 48.8 MB/s  0:00:00
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.18.0-cp314-cp314-win_amd64.whl (37.3 MB)
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
   ------------------------ --------------- 23.1/37.3 MB 139.4 MB/s eta 0:00:01
   ---------------------------------------  37.2/37.3 MB 126.2 MB/s eta 0:00:01
   ---------------------------------------- 37.3/37.3 MB 78.6 MB/s  0:00:00
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ---------------------------------------- 4/4 [scikit-learn]

Successfully installed joblib-1.5.3 scikit-learn-1.9.0 scipy-1.18.0 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

In [9]:
# libraries
import pandas as pd
import hvplot.pandas
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [11]:
df_market_data = pd.read_csv(
    r"C:\Users\secar\OneDrive\Documents\Bootcamp\19-Unsupervised-Learning\Resources\crypto_market_data.csv",
    index_col="coin_id"
)

# Display sample data
df_market_data.head(10)

,price_change_percentage_24h,price_change_percentage_7d,price_change_percentage_14d,price_change_percentage_30d,price_change_percentage_60d,price_change_percentage_200d,price_change_percentage_1y
coin_id,,,,,,,
bitcoin,1.08388,7.60278,6.57509,7.67258,-3.25185,83.51840,37.51761
ethereum,0.22392,10.38134,4.80849,0.13169,-12.88890,186.77418,101.96023
tether,-0.21173,0.04935,0.00640,-0.04237,0.28037,-0.00542,0.01954
ripple,-0.37819,-0.60926,2.24984,0.23455,-17.55245,39.53888,-16.60193
bitcoin-cash,2.90585,17.09717,14.75334,15.74903,-13.71793,21.66042,14.49384
binancecoin,2.10423,12.85511,6.80688,0.05865,36.33486,155.61937,69.69195
chainlink,-0.23935,20.69459,9.30098,-11.21747,-43.69522,403.22917,325.13186
cardano,0.00322,13.99302,5.55476,10.10553,-22.84776,264.51418,156.09756
litecoin,-0.06341,6.60221,7.28931,1.21662,-17.23960,27.49919,-12.66408
bitcoin-cash-sv,0.92530,3.29641,-1.86656,2.88926,-24.87434,7.42562,93.73082

In [12]:
# summary statistics
df_market_data.describe()

,price_change_percentage_24h,price_change_percentage_7d,price_change_percentage_14d,price_change_percentage_30d,price_change_percentage_60d,price_change_percentage_200d,price_change_percentage_1y
count,41.000000,41.000000,41.000000,41.000000,41.000000,41.000000,41.000000
mean,-0.269686,4.497147,0.185787,1.545693,-0.094119,236.537432,347.667956
std,2.694793,6.375218,8.376939,26.344218,47.365803,435.225304,1247.842884
min,-13.527860,-6.094560,-18.158900,-34.705480,-44.822480,-0.392100,-17.567530
25%,-0.608970,0.047260,-5.026620,-10.438470,-25.907990,21.660420,0.406170
50%,-0.063410,3.296410,0.109740,-0.042370,-7.544550,83.905200,69.691950
75%,0.612090,7.602780,5.510740,4.578130,0.657260,216.177610,168.372510
max,4.840330,20.694590,24.239190,140.795700,223.064370,2227.927820,7852.089700

In [13]:
# Plot 
df_market_data.hvplot.line(
    width=800,
    height=400,
    rot=90
)

:NdOverlay   [Variable]
   :Curve   [coin_id]   (value)

---

### Prepare the Data

In [14]:
# `StandardScaler()` module from scikit-learn to normalize the data from the CSV file
market_data_scaled = StandardScaler().fit_transform(df_market_data)

In [15]:
# DataFrame with the scaled data
# Set the index to the original `coin_id` values.
df_market_data_scaled = pd.DataFrame(
    market_data_scaled,
    columns=df_market_data.columns,
    index=df_market_data.index
)

# sample data
df_market_data_scaled.head()

,price_change_percentage_24h,price_change_percentage_7d,price_change_percentage_14d,price_change_percentage_30d,price_change_percentage_60d,price_change_percentage_200d,price_change_percentage_1y
coin_id,,,,,,,
bitcoin,0.508529,0.493193,0.772200,0.235460,-0.067495,-0.355953,-0.251637
ethereum,0.185446,0.934445,0.558692,-0.054341,-0.273483,-0.115759,-0.199352
tether,0.021774,-0.706337,-0.021680,-0.061030,0.008005,-0.550247,-0.282061
ripple,-0.040764,-0.810928,0.249458,-0.050388,-0.373164,-0.458259,-0.295546
bitcoin-cash,1.193036,2.000959,1.760610,0.545842,-0.291203,-0.499848,-0.270317

In [17]:
print(df_market_data.columns)

Index(['price_change_percentage_24h', 'price_change_percentage_7d',
       'price_change_percentage_14d', 'price_change_percentage_30d',
       'price_change_percentage_60d', 'price_change_percentage_200d',
       'price_change_percentage_1y'],
      dtype='str')

---

### Find the Best Value for k Using the Original Data.

In [19]:
# list with the number of k-values from 1 to 11
k_values = list(range(1, 12))

In [20]:
# empty list to store the inertia values
inertia = []

# for loop to compute the inertia with each possible value of k
for k in k_values:
    # Create a KMeans model using the loop counter for n_clusters
    model = KMeans(n_clusters=k, random_state=42, n_init="auto")
    
    # Fit the model to the scaled data
    model.fit(df_market_data_scaled)
    
    # Append the model.inertia_ to the inertia list
    inertia.append(model.inertia_)

C:\Users\secar\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1428: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
C:\Users\secar\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1428: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
C:\Users\secar\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1428: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
C:\Users\secar\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1428: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
C:\Users\secar\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1428: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
C:\Users\secar\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1428: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
C:\Users\secar\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1428: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
C:\Users\secar\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1428: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
C:\Users\secar\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1428: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
C:\Users\secar\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1428: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
C:\Users\secar\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1428: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

In [21]:
# dictionary with the data to plot the Elbow curve
elbow_data = {"k": k_values, "inertia": inertia}

# DataFrame with the data to plot the Elbow curve
elbow_df = pd.DataFrame(elbow_data)

elbow_df

     k     inertia
0    1  287.000000
1    2  212.123342
2    3  170.193571
3    4   79.022435
4    5   71.097914
5    6   66.108827
6    7   54.488123
7    8   43.224693
8    9   32.860884
9   10   28.404885
10  11   24.116198

In [23]:
# line chart with all the inertia values computed with 
# the different values of k to visually identify the optimal value for k.
elbow_df.hvplot.line(
    x="k",
    y="inertia",
    title="Elbow Curve - Original Scaled Data",
    xticks=k_values
)

:Curve   [k]   (inertia)

#### Answer the following question: 

**Question:** What is the best value for `k`?

**Answer:** 4

---

### Cluster Cryptocurrencies with K-means Using the Original Data

In [24]:
# Initialize the K-Means model using the best value for k
best_k = 4

kmeans_model = KMeans(n_clusters=best_k, random_state=42)

In [25]:
# Fit the K-Means model using the scaled data
kmeans_model.fit(df_market_data_scaled)

C:\Users\secar\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1428: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

KMeans(n_clusters=4, random_state=42)

In [26]:
# Predict the clusters to group the cryptocurrencies using the scaled data
market_data_clusters = kmeans_model.predict(df_market_data_scaled)

# Print the resulting array of cluster values.
market_data_clusters

array([0, 0, 2, 2, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0,
       2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 3, 0, 2, 2, 1, 2, 2, 2, 2],
      dtype=int32)

In [27]:
# Copy of the original DataFrame
df_market_data_predictions = df_market_data.copy()

In [28]:
# Add a new column to the DataFrame with the predicted clusters
df_market_data_predictions["predicted_cluster"] = market_data_clusters

# Sample data
df_market_data_predictions.head()

,price_change_percentage_24h,price_change_percentage_7d,price_change_percentage_14d,price_change_percentage_30d,price_change_percentage_60d,price_change_percentage_200d,price_change_percentage_1y,predicted_cluster
coin_id,,,,,,,,
bitcoin,1.08388,7.60278,6.57509,7.67258,-3.25185,83.51840,37.51761,0
ethereum,0.22392,10.38134,4.80849,0.13169,-12.88890,186.77418,101.96023,0
tether,-0.21173,0.04935,0.00640,-0.04237,0.28037,-0.00542,0.01954,2
ripple,-0.37819,-0.60926,2.24984,0.23455,-17.55245,39.53888,-16.60193,2
bitcoin-cash,2.90585,17.09717,14.75334,15.74903,-13.71793,21.66042,14.49384,0

In [29]:
# Create a scatter plot using hvPlot by setting 
# `x="price_change_percentage_24h"` and `y="price_change_percentage_7d"`. 
# Color the graph points with the labels found using K-Means and 
# add the crypto name in the `hover_cols` parameter to identify 
# the cryptocurrency represented by each data point.
df_market_data_predictions.reset_index().hvplot.scatter(
    x="price_change_percentage_24h",
    y="price_change_percentage_7d",
    by="predicted_cluster",
    hover_cols=["coin_id"],
    title="Cryptocurrency Clusters - Original Scaled Data"
)

:NdOverlay   [predicted_cluster]
   :Scatter   [price_change_percentage_24h]   (price_change_percentage_7d,coin_id)

---

### Optimize Clusters with Principal Component Analysis.

In [30]:
# Create a PCA model instance and set `n_components=3`.
pca_model = PCA(n_components=3)

In [31]:
# Use the PCA model with `fit_transform` to reduce to 
# three principal components.
market_data_pca = pca_model.fit_transform(df_market_data_scaled)

# View the first five rows of the array. 
market_data_pca[:5]

array([[-0.60066733,  0.84276006,  0.46159457],
       [-0.45826071,  0.45846566,  0.95287678],
       [-0.43306981, -0.16812638, -0.64175193],
       [-0.47183495, -0.22266008, -0.47905316],
       [-1.15779997,  2.04120919,  1.85971527]])

In [32]:
# Retrieve the explained variance to determine how much information 
# can be attributed to each principal component.
pca_model.explained_variance_ratio_

array([0.3719856 , 0.34700813, 0.17603793])

#### Answer the following question: 

**Question:** What is the total explained variance of the three principal components?

**Answer:** The total explained variance of the three principal components is the sum of these variances, which is 0.8950. 
You can arrive at the same answer by using the explained variance ratio

In [21]:
#The total explained variance of the three principal components is the sum of these variances, which is 0.8950. 
#You can arrive at the same answer by using the explained variance ratio

In [ ]:
# Cew DataFrame with the PCA data.
df_market_data_pca = pd.DataFrame(
    market_data_pca,
    columns=["PC1", "PC2", "PC3"],
    index=df_market_data.index
)

# Display sample data
df_market_data_pca.head()

---

### Find the Best Value for k Using the PCA Data

In [23]:
# Create a list with the number of k-values from 1 to 11
k_values = list(range(1, 12))

In [ ]:
# Create an empty list to store the inertia values
pca_inertia = []

# Create a for loop to compute the inertia with each possible value of k
for k in k_values:
    # Create a KMeans model using the loop counter for n_clusters
    model = KMeans(n_clusters=k, random_state=42, n_init="auto")
    
    # Fit the model to the PCA data
    model.fit(df_market_data_pca)
    
    # Append the model.inertia_ to the inertia list
    pca_inertia.append(model.inertia_)

In [ ]:
# Create a dictionary with the data to plot the Elbow curve
pca_elbow_data = {"k": k_values, "inertia": pca_inertia}

# Create a DataFrame with the data to plot the Elbow curve
pca_elbow_df = pd.DataFrame(pca_elbow_data)

pca_elbow_df

In [ ]:
# Plot a line chart with all the inertia values computed with 
# the different values of k to visually identify the optimal value for k.
pca_elbow_df.hvplot.line(
    x="k",
    y="inertia",
    title="Elbow Curve - PCA Data",
    xticks=k_values
)

#### Answer the following questions: 

* **Question:** What is the best value for `k` when using the PCA data?

  * **Answer:** 4


* **Question:** Does it differ from the best k value found using the original data?

  * **Answer:** No

### Cluster Cryptocurrencies with K-means Using the PCA Data

In [32]:
# Initialize the K-Means model using the best value for k
best_k = 4

kmeans_nextmodel = KMeans(n_clusters=best_k, random_state=42)

In [ ]:
# Fit the K-Means model using the PCA data
kmeans_nextmodel.fit(df_market_data_pca)

In [ ]:
# Predict the clusters to group the cryptocurrencies using the PCA data
pca_clusters = kmeans_nextmodel.predict(df_market_data_pca)

# Print the resulting array of cluster values.
pca_clusters

In [ ]:
# Create a copy of the DataFrame with the PCA data
df_market_data_pca_predictions = df_market_data_pca.copy()

# Add a new column to the DataFrame with the predicted clusters
df_market_data_pca_predictions["predicted_cluster"] = pca_clusters

# Display sample data
df_market_data_pca_predictions.head()

In [ ]:
# Create a scatter plot using hvPlot by setting 
# `x="PC1"` and `y="PC2"`. 
# Color the graph points with the labels found using K-Means and 
# add the crypto name in the `hover_cols` parameter to identify 
# the cryptocurrency represented by each data point.
df_market_data_pca_predictions.reset_index().hvplot.scatter(
    x="PC1",
    y="PC2",
    by="predicted_cluster",
    hover_cols=["coin_id"],
    title="Cryptocurrency Clusters - PCA Data"
)

### Visualize and Compare the Results

In this section, you will visually analyze the cluster analysis results by contrasting the outcome with and without using the optimization techniques.

In [ ]:
# Composite plot to contrast the Elbow curves
elbow_original_plot = elbow_df.hvplot.line(
    x="k",
    y="inertia",
    title="Elbow Curve - Original Scaled Data",
    xticks=k_values
)

elbow_pca_plot = pca_elbow_df.hvplot.line(
    x="k",
    y="inertia",
    title="Elbow Curve - PCA Data",
    xticks=k_values
)

elbow_original_plot + elbow_pca_plot

In [ ]:
# Composite plot to contrast the clusters
clusters_original_plot = df_market_data_predictions.reset_index().hvplot.scatter(
    x="price_change_percentage_24h",
    y="price_change_percentage_7d",
    by="predicted_cluster",
    hover_cols=["coin_id"],
    title="Clusters - Original Scaled Data"
)

clusters_pca_plot = df_market_data_pca_predictions.reset_index().hvplot.scatter(
    x="PC1",
    y="PC2",
    by="predicted_cluster",
    hover_cols=["coin_id"],
    title="Clusters - PCA Data"
)

clusters_original_plot + clusters_pca_plot

#### Answer the following question: 

  * **Question:** After visually analyzing the cluster analysis results, what is the impact of using fewer features to cluster the data using K-Means?

  * **Answer:** Using PCA keeps most of the information from the original features while making the clusters easier to visualize and interpret. In this case, the three principal components explain about 89.5% of the total variance, and the PCA clustering produces a very similar cluster structure to the original scaled data. The main benefit is simplification: fewer dimensions, cleaner plots, and less noise, with little loss of clustering signal.